### ISSUE TITLE
Assign reading before workshop

### ISSUE THREAD

**Issue by korenmiklos** [codedthinking/tender-home-bias#1]
One Medium-sized blog post for each unit:
- command line
- https://handbook.microdata.io/tools/csvkit
- make

**Comment by csokaimola** [comment]
I think it would be enough as prerequisite that someone knows command line. Other stuff could be just listed as resources (Issue #3 ) with links.
command line: https://handbook.microdata.io/onboarding/terminal
make: https://github.com/unix-tools/tutorial-makefiles and https://handbook.microdata.io/tools/make

**Comment by korenmiklos** [comment]
- https://github.com/onyxfish/command-line-tutorial

**Comment by korenmiklos** [comment]
- https://bost.ocks.org/mike/make/

**Comment by korenmiklos** [comment]
- https://www.dataquest.io/blog/data-cleaning-command-line/

**Comment by korenmiklos** [comment]
https://blog.getdbt.com/future-of-the-modern-data-stack/

**Comment by korenmiklos** [comment]
This is what I sent out:

Some recommended readings before the workshop:
[Command line tutorial](https://github.com/onyxfish/command-line-tutorial)
[Cleaning CSV data using the command line and csvkit](https://www.dataquest.io/blog/data-cleaning-command-line/)
[A love letter to Make](https://medium.com/data-architect/a-love-letter-to-make-933de68bb816)
[The Modern Data Stack](https://blog.getdbt.com/future-of-the-modern-data-stack/)
We will cover all of this material from scratch, but especially if you are not yet familiar with the Linux environment, the readings may be a good way to warm up.
