### ISSUE TITLE
Rename variable names in .csv files

### ISSUE THREAD

**Issue by csokaimola** [codedthinking/tender-home-bias#4]

**Comment by korenmiklos** [comment]
There is no `csvkit` option for this, we can implement this as a use case of `head -n1` and `tail -n +2`

**Comment by korenmiklos** [comment]
This is now part of the lesson, see
https://github.com/codedthinking/tender-home-bias/blob/f708e5d045e9c2759c0e548f8dc65f83f153247d/lesson/instructions2.md#L13
