### ISSUE TITLE
Plan B if replit dies

### ISSUE THREAD

**Issue by korenmiklos** [codedthinking/tender-home-bias#9]

**Comment by korenmiklos** [comment]
Check for web based alternatives.

Python to install csvkit. Shell. make. Text editor should allow for tabs.

**Comment by zaveczgergo** [comment]
https://www.goorm.io/
After login, I could install `csvkit`, I could `mkdir` and `curl` in shell. I could produce a shared link, see: [link](https://goor.me/aWPkN). I am unsure about how to fork though.
